name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyenv # used for installing the right version of Python
        curl https://pyenv.run | bash
        pipenv shell
        pipenv install .
