name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"] # Test oldest and newest supported Python
        r-version: ["4.1.2", "4.2.1", "4.4"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.r-version }}
    - name: Install fiddly packages
      run: |
        install.packages("devtools")
        devtool:::install_version("Matrix", "1.6.5")
      shell: Rscript {0}
      working-directory: 'sch_simulation/amis_integration'
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        working-directory: 'sch_simulation/amis_integration/'
    - name: Run R tests
      run: Rscript tests/testthat.R
      working-directory: 'sch_simulation/amis_integration'

