name: CI

env: 
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"] # Test oldest and newest supported Python
        r-version: ["4.1.2"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.r-version }}
    - name: Instal R dev tools
      run: sudo apt-get install -y r-cran-devtools build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev libharfbuzz-dev libfribidi-dev
    - name: Install fiddly packages
      run: |
        install.packages("devtools")
        devtools::install_version("Matrix", "1.6.5")
        devtools::install_github("evandrokonzen/AMISforInfectiousDiseases-dev")
      shell: Rscript {0}
      working-directory: 'sch_simulation/amis_integration'
    - name: Run R tests
      run: Rscript tests/testthat.R
      working-directory: 'sch_simulation/amis_integration'

