name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"] # Test oldest and newest supported Python
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.2'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install . --python ${{ matrix.python-version }} 
    - name: Run Python tests
      run: pipenv run pytest tests
    - name: Test renv
      run: |
        cd sch_simulation/amis_integration
        pwd
        Rscript -e 'install.packages("renv")'
        echo installed
        Rscript -e "print(getwd())"
        Rscript -e "renv::init()"
        echo Activated
        Rscript -e "renv::restore()"
        echo Restored
        Rscript -e "renv::status()"
        Rscript tests/testthat.R
    - uses: r-lib/actions/setup-renv@v2
      with:
        working-directory: 'sch_simulation/amis_integration/'
    - name: Run R tests
      run: Rscript tests/testthat.R
      with:
        working-directory: 'sch_simulation/amis_integration'

