name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test oldest and newest supported Python
        python-version: ["3.9", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.2'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install .[dev]
    - name: Run Python tests
      run: |
        pytest tests
    - uses: r-lib/actions/setup-renv@v2
      with:
        working-directory: 'sch_simulation/amis_integration/'
    - name: Run R tests
      run: Rscript tests/testthat.R
      working-directory: 'sch_simulation/amis_integration'
